language: python
python:
  - 3.6
services: postgresql

env:
  - DJANGO=2.2

install:
  - pip install -r requirement.txt

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres

script:
  - python manage.py test && flake8